steps:
  - label: Build & Lint & Test
    key: "build"
    command:
      - ".ci/build"
    agents:
      napali: true
      queue: napali

  - label: Publish
    key: "publish"
    branches: "master"
    command:
      - ".ci/publish"
    depends_on:
      - "build"
    agents:
      napali: true
      queue: napali
