#!/bin/sh -eu

ROOT="$(git rev-parse --show-toplevel)"

section() {
  echo "--- $(TZ=UTC date +%Y%m%d-%H:%M:%S) - [boomerang] - $1"
}

cd "${ROOT}"

rm -rf ./build ./node_modules

section "Installing dependencies"

npm install

section "Build"

pnpm run build

section "Done :tada:"
