#!/bin/sh -eu

ROOT="$(git rev-parse --show-toplevel)"
SHA=$(git rev-parse HEAD)

OUTPUT=s3://formation-dispensary/interface/boomerang/commits/${SHA}

BRANCH="${BUILDKITE_BRANCH:=$(git rev-parse --abbrev-ref HEAD)}"
SUFFIX="branches"
if [ "$BRANCH" == "master" ]; then
    SUFFIX="master"
fi

aws s3 sync ${ROOT}/build/ ${OUTPUT}

cat <<EOF | buildkite-agent annotate --style "info" --context "PUBLISH" --append >&2
<details>
  <summary>
    Published to ${SHA}
  </summary>

  <h5>Dispensary path</h5>
  <a href="${OUTPUT}">${OUTPUT}</a>
</details>
EOF

